# DataVault Redis configuration
maxmemory           512mb
maxmemory-policy    allkeys-lru

# Persistence
save                60 1000
appendonly          yes
appendfsync         everysec
no-appendfsync-on-rewrite yes

# Security (password injected via CLI arg --requirepass)
protected-mode yes

# Performance
tcp-backlog         511
timeout             0
tcp-keepalive       300
lazyfree-lazy-eviction yes
